name: fasd # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.0.1' # just for humans, typically '1.2+git' or '1.3.2'
license: MIT
summary: Commnd-line productivity booster. # 79 char long summary
description: |
  Fasd (pronounced similar to "fast") is a command-line productivity booster. 
  Fasd offers quick access to files and directories for POSIX shells. It is 
  inspired by tools like autojump, z and v. Fasd keeps track of files and 
  directories you have accessed, so that you can quickly reference them in the 
  command line. The name fasd comes from the default suggested aliases f(files),
  a(files/directories), s(show/search/select), d(directories).

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  fasd:
    command: usr/local/bin/fasd
parts:
  fasd:
    plugin: make
    source: https://github.com/clvv/fasd.git
    source-tag: '1.0.1'